In [0]:
#1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [2]:
#2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
np.show_config()

1.18.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


In [3]:
#3. Create a null vector of size 10 (★☆☆)
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4. How to find the memory size of any array (★☆☆)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [5]:
#5. How to get the documentation of the numpy add function from the command line? (★☆☆)
%run `python -c "import numpy; numpy.info(numpy.add)"


ERROR:root:File `'`python.py'` not found.


In [6]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#7. Create a vector with values ranging from 10 to 49 (★☆☆)
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#8. Reverse a vector (first element becomes last) (★☆☆)
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [9]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [10]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [11]:
#11. Create a 3x3 identity matrix (★☆☆)
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#12. Create a 3x3x3 array with random values (★☆☆)
Z = np.random.random((3,3,3))
print(Z)

[[[0.24857004 0.69010082 0.83466003]
  [0.43940166 0.27077389 0.4863039 ]
  [0.85547465 0.06691318 0.9303294 ]]

 [[0.46270775 0.65738638 0.49908184]
  [0.64475404 0.96770791 0.06561203]
  [0.41774839 0.63899401 0.43033356]]

 [[0.94358989 0.51895182 0.13694552]
  [0.96040667 0.2971657  0.85769058]
  [0.20250819 0.55062914 0.45242418]]]


In [13]:
#13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.009094951866595924 0.998032595480157


In [15]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
Z = np.random.random(30)
m = Z.mean()
print(m)

0.4875738946508806


In [16]:
#15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
#17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [20]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [21]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


In [23]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [24]:
#22. Normalize a 5x5 random matrix (★☆☆)
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.59441455 -0.40030532 -0.51329317 -0.26749831 -1.16595146]
 [-0.06696053 -0.84812576  0.97475378 -1.56412009  0.88497984]
 [ 0.74971345  0.92218868  1.40106226 -1.8429155  -0.03767298]
 [-0.12494353  1.63504757 -1.0393202  -1.07169706 -0.92960808]
 [ 0.48275627 -0.54191672  0.18608913 -0.02368867  1.60701185]]


In [26]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [27]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [28]:
#25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [30]:
#26. What is the output of the following script? (★☆☆)
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10
10
10


In [36]:
#29. How to round away from zero a float array ? (★☆☆)
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 9. -8.  7.  1.  5.  1. -7. -3.  5. -4.]


In [38]:
#30. How to find common values between two arrays? (★☆☆)
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 4 7 9]


In [41]:
#31. How to ignore all numpy warnings (not recommended)? (★☆☆)
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


In [49]:
#34. How to get all the dates corresponding to the month of July 2016? (★★☆)
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [50]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [52]:
#36. Extract the integer part of a random array using 5 different methods (★★☆)
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[2. 0. 2. 8. 1. 9. 3. 8. 3. 4.]
[2. 0. 2. 8. 1. 9. 3. 8. 3. 4.]
[2. 0. 2. 8. 1. 9. 3. 8. 3. 4.]
[2 0 2 8 1 9 3 8 3 4]
[2. 0. 2. 8. 1. 9. 3. 8. 3. 4.]


In [3]:
#37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [4]:
#38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [6]:
#40. Create a random vector of size 10 and sort it (★★☆)
Z = np.random.random(10)
Z.sort()
print(Z)

[0.03023805 0.04206002 0.22194335 0.24286759 0.28174978 0.28636984
 0.49008079 0.55663922 0.74871131 0.76621242]


In [7]:
#41. How to sum a small array faster than np.sum? (★★☆)
# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

45

In [8]:
#42. Consider two random array A and B, check if they are equal (★★☆)
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


False
False


In [10]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.78562167 0.53548432 1.02206872 0.54250465 1.07422191 0.64393934
 1.05779558 1.10799327 0.78223194 1.00702626]
[1.12139421 0.68741752 1.04881333 0.34202931 0.92290574 1.51978981
 0.94226543 0.92824188 0.67626704 0.35449992]


In [11]:
#45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.75223177 0.6576956  0.55578533 0.35460376 0.09897731 0.3856883
 0.26423386 0.3675461  0.         0.04050928]


In [12]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area (★★☆)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [13]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [14]:
#48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [16]:
#50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

31


In [18]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [19]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.4077022  0.37708286 0.25078976 0.51724835 0.66411491
  0.2154398  0.43669115 0.38485941 0.36917996]
 [0.4077022  0.         0.6231566  0.42462196 0.28044268 0.55023612
  0.57584655 0.36801518 0.51593733 0.19228898]
 [0.37708286 0.6231566  0.         0.19865103 0.54025381 1.0277984
  0.52483545 0.796959   0.7608135  0.46440102]
 [0.25078976 0.42462196 0.19865103 0.         0.37732485 0.85247999
  0.45165222 0.62259373 0.62384378 0.27476136]
 [0.51724835 0.28044268 0.54025381 0.37732485 0.         0.83055143
  0.72767609 0.64225543 0.75926731 0.15207355]
 [0.66411491 0.55023612 1.0277984  0.85247999 0.83055143 0.
  0.64986311 0.23089803 0.35687984 0.72465214]
 [0.2154398  0.57584655 0.52483545 0.45165222 0.72767609 0.64986311
  0.         0.45603124 0.30197429 0.57694576]
 [0.43669115 0.36801518 0.796959   0.62259373 0.64225543 0.23089803
  0.45603124 0.         0.21601485 0.51866076]
 [0.38485941 0.51593733 0.7608135  0.62384378 0.75926731 0.35687984
  0.30197429 0.216014

In [20]:
#53. How to convert a float (32 bits) array into an integer (32 bits) in place?
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[66  6 83 86 91 72 52 38 98 85]


In [0]:
#54. How to read the following file? (★★☆)
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

In [22]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


In [23]:
#55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [24]:
#56. Generate a generic 2D Gaussian-like array (★★☆)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [25]:
#57. How to randomly place p elements in a 2D array? (★★☆)
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [26]:
#58. Subtract the mean of each row of a matrix (★★☆)
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.51325204  0.40016811  0.20389204  0.16244106 -0.20926646 -0.4094329
  -0.11533028  0.08089667  0.43111562 -0.03123183]
 [ 0.2947128   0.0878118  -0.28270528 -0.30432398 -0.49556985  0.1782792
  -0.19782955  0.07370452  0.23920759  0.40671275]
 [-0.4800444   0.30971027 -0.19656662  0.26030936  0.21433796 -0.1401219
   0.21013214  0.03089631 -0.08437312 -0.12427999]
 [-0.19225946 -0.20155205 -0.19711899 -0.35653382 -0.21937762 -0.11582728
   0.31196293  0.42451951  0.509081    0.0371058 ]
 [ 0.2008398   0.04958955  0.41359876 -0.24382241 -0.20462867 -0.52476453
   0.37488397  0.24916508 -0.4469891   0.13212755]]


In [27]:
#59. How to sort an array by the nth column? (★★☆)
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 0 5]
 [7 0 5]
 [4 4 3]]
[[7 0 5]
 [7 0 5]
 [4 4 3]]


In [28]:
#60. How to tell if a given 2D array has null columns? (★★☆)
# Author: Warren Weckesser

Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [29]:
#61. Find the nearest value from a given value in an array (★★☆)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5613989221707729


In [30]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [31]:
#63. Create an array class that has a name attribute (★★☆)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [32]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 1. 1. 3. 3. 9. 2. 3. 1. 5.]
[ 3.  1.  1.  5.  5. 17.  3.  5.  1.  9.]


In [33]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [34]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
# Author: Nadav Horesh

w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))


[0 1]


In [35]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[43 47 52 40]
 [79 43 62 57]
 [45 52 72 46]]
[[43 47 52 40]
 [79 43 62 57]
 [45 52 72 46]]


In [37]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices? (★★★)
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.63070616 0.61776048 0.36422678 0.50748789 0.65170572 0.64468278
 0.5320893  0.49389587 0.39968576 0.50867553]
0    0.630706
1    0.617760
2    0.364227
3    0.507488
4    0.651706
5    0.644683
6    0.532089
7    0.493896
8    0.399686
9    0.508676
dtype: float64


In [38]:
#69. How to get the diagonal of a dot product? (★★★)
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([2.67360836, 1.53259183, 0.75858784, 0.74408757, 2.3751376 ])

In [39]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [40]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [41]:
#72. How to swap two rows of an array? (★★★)
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [42]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 15) ( 1, 87) ( 7, 89) ( 9, 14) ( 9, 97) (10, 21) (10, 49) (12, 34)
 (12, 97) (14, 53) (14, 68) (14, 97) (15, 87) (20, 41) (20, 68) (21, 47)
 (21, 48) (21, 49) (26, 68) (26, 79) (34, 97) (41, 68) (44, 60) (44, 65)
 (47, 48) (53, 68) (60, 65) (68, 79) (89, 89)]


In [43]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [44]:
#75. How to compute averages using a sliding window over an array? (★★★)
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [45]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [46]:
#77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.27437062,  0.31006044,  0.53508224,  0.56573821, -0.77068413,
        0.46787332, -0.05102761,  0.92266323, -0.94444197,  0.62578908,
       -0.45161547, -0.77777372,  0.53640327, -0.24907836,  0.26881437,
       -0.32566683,  0.59962943, -0.71462788,  0.20766293, -0.22291579,
        0.01391239,  0.26523433, -0.84593414,  0.73880189,  0.18195981,
       -0.1329482 ,  0.94862629,  0.36360471,  0.04528647, -0.94502788,
       -0.59511106, -0.14395221,  0.78122134,  0.65775219,  0.18580697,
       -0.96320253,  0.70017009,  0.23585259, -0.269852  ,  0.989064  ,
       -0.50246993,  0.7774305 , -0.90265413, -0.32588837,  0.98945861,
       -0.36704432, -0.24872722, -0.17122944,  0.35224393, -0.1877955 ,
       -0.45948719, -0.7364189 ,  0.33211768,  0.07501189, -0.81289837,
       -0.71216096, -0.3094032 ,  0.58054184, -0.51417441,  0.23800602,
        0.46099098, -0.00655803,  0.45350561,  0.73365612, -0.59715976,
       -0.58236907,  0.00641246,  0.1121986 , -0.49262701, -0.47

In [47]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[14.41014602  5.43670985  7.35879934 10.88712173  6.95404169  4.78254888
  9.01982196  1.5363248   5.34884403 13.97893411]


In [48]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.25067443  0.50754628 12.7865218   1.30247082  2.88990915  6.57321362
  10.90726021  4.39120036  9.56123179  2.83325321]
 [ 5.27611109  5.71112213  2.01454858 13.54016004  6.91531768  1.30140881
   5.40972588 10.25489626  6.13127618  0.15357952]
 [ 4.72176957  5.74804239  0.72303344 10.78682609  5.74620469  0.65566666
   1.96181324  7.57525292  2.25377679  0.72711039]
 [ 4.908994    6.85431122  4.18514524  7.29624257  4.95094764  0.69860438
   2.8544795   4.21745268  3.68372831  2.64624287]
 [ 5.08559812  6.72117658  2.83708043  8.65299176  5.45252407  0.92333006
   1.1071715   5.53361938  1.66217932  2.23430255]
 [ 3.65469273  0.94915365 13.64161887  2.15063931  4.20188447  7.966018
  11.35256614  5.27120977  9.33989539  4.30834439]
 [ 2.35222038  3.02381057  1.12404781 10.40553275  3.81472462  1.65334596
   2.63109848  7.10276476  4.34897649  2.26432276]
 [ 4.5468639   1.94580307 13.90657478  2.40904788  4.96003553  8.83994686
  11.25595291  5.55985821  8.73930263  5.37977218]
 [

In [49]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 8 5 1 5 5 2 7 1 1]
 [5 7 4 4 7 9 4 2 2 6]
 [1 2 4 5 7 9 8 8 9 9]
 [9 8 7 8 6 1 4 4 4 5]
 [7 7 3 1 0 4 6 6 3 9]
 [4 3 7 1 8 8 5 7 1 0]
 [0 3 6 8 3 8 3 7 8 5]
 [8 0 6 6 1 1 9 9 5 8]
 [0 3 3 7 0 6 7 6 0 0]
 [8 4 4 1 3 1 3 5 1 8]]
[[0 0 0 0 0]
 [0 8 8 5 1]
 [0 5 7 4 4]
 [0 1 2 4 5]
 [0 9 8 7 8]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:26: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [50]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [51]:
#82. Compute a matrix rank (★★★)
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [52]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


In [53]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 3]
   [0 0 0]
   [0 4 0]]

  [[2 3 3]
   [0 0 2]
   [4 0 2]]

  [[3 3 1]
   [0 2 0]
   [0 2 4]]

  [[3 1 3]
   [2 0 1]
   [2 4 2]]

  [[1 3 2]
   [0 1 4]
   [4 2 2]]

  [[3 2 3]
   [1 4 3]
   [2 2 3]]

  [[2 3 4]
   [4 3 3]
   [2 3 0]]

  [[3 4 1]
   [3 3 4]
   [3 0 4]]]


 [[[0 0 0]
   [0 4 0]
   [4 0 1]]

  [[0 0 2]
   [4 0 2]
   [0 1 0]]

  [[0 2 0]
   [0 2 4]
   [1 0 1]]

  [[2 0 1]
   [2 4 2]
   [0 1 4]]

  [[0 1 4]
   [4 2 2]
   [1 4 1]]

  [[1 4 3]
   [2 2 3]
   [4 1 0]]

  [[4 3 3]
   [2 3 0]
   [1 0 3]]

  [[3 3 4]
   [3 0 4]
   [0 3 0]]]


 [[[0 4 0]
   [4 0 1]
   [3 3 4]]

  [[4 0 2]
   [0 1 0]
   [3 4 0]]

  [[0 2 4]
   [1 0 1]
   [4 0 2]]

  [[2 4 2]
   [0 1 4]
   [0 2 2]]

  [[4 2 2]
   [1 4 1]
   [2 2 2]]

  [[2 2 3]
   [4 1 0]
   [2 2 4]]

  [[2 3 0]
   [1 0 3]
   [2 4 2]]

  [[3 0 4]
   [0 3 0]
   [4 2 2]]]


 [[[4 0 1]
   [3 3 4]
   [4 3 2]]

  [[0 1 0]
   [3 4 0]
   [3 2 1]]

  [[1 0 1]
   [4 0 2]
   [2 1 3]]

  [[0 1 4]
   [0 2 2]
   [1 3 4]]

  [[1 4 1]
   

In [54]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  6  9  5  9]
 [ 6  8  9 16  4]
 [ 9  9  7 42  9]
 [ 5 16 42  5  5]
 [ 9  4  9  5  0]]


In [55]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [56]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [57]:
#88. How to implement the Game of Life using numpy arrays? (★★★)
# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [58]:
#89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9996 9997 9995]


In [59]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [60]:
#91. How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [61]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)
# Author: Ryan G.

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 3: 3.68 s per loop
10 loops, best of 3: 143 ms per loop
10 loops, best of 3: 126 ms per loop


In [62]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 7]


In [63]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 0 1]
 [2 4 3]
 [0 4 0]
 [2 3 3]
 [4 1 4]
 [0 4 0]
 [2 0 4]
 [4 0 0]
 [3 0 4]
 [0 3 1]]
[[4 0 1]
 [2 4 3]
 [0 4 0]
 [2 3 3]
 [4 1 4]
 [0 4 0]
 [2 0 4]
 [4 0 0]
 [3 0 4]
 [0 3 1]]
[[4 0 1]
 [2 4 3]
 [0 4 0]
 [2 3 3]
 [4 1 4]
 [0 4 0]
 [2 0 4]
 [4 0 0]
 [3 0 4]
 [0 3 1]]


In [64]:
#95. Convert a vector of ints into a matrix binary representation (★★★)
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [65]:
#96. Given a two dimensional array, how to extract unique rows? (★★★)
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[[0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [66]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.82721312, 0.17971599, 0.75714378, 0.18966352, 0.68148011,
        0.71066643, 0.78903275, 0.03724922, 0.57658174, 0.21439213],
       [0.18762918, 0.04076333, 0.171736  , 0.04301964, 0.1545739 ,
        0.16119396, 0.17896908, 0.0084489 , 0.13078076, 0.04862861],
       [0.04310441, 0.00936464, 0.03945324, 0.00988298, 0.03551055,
        0.0370314 , 0.04111491, 0.00194098, 0.03004451, 0.01117154],
       [0.07686325, 0.01669891, 0.07035253, 0.01762322, 0.06332199,
        0.06603393, 0.0733156 , 0.00346113, 0.05357501, 0.01992096],
       [0.70830808, 0.15388331, 0.64831063, 0.16240096, 0.58352298,
        0.60851401, 0.67561582, 0.03189495, 0.49370289, 0.18357504],
       [0.38383011, 0.08338892, 0.35131766, 0.08800461, 0.31620943,
        0.32975199, 0.36611427, 0.01728378, 0.26753617, 0.09947878],
       [0.0970411 , 0.02108264, 0.0888212 , 0.02224959, 0.07994503,
        0.0833689 , 0.09256212, 0.00436974, 0.06763931, 0.02515053],
       [0.53595569, 0.11643893, 0.4905574

In [70]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [71]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.13478488  0.22172027]
